application: energygraph
version: 5
runtime: python
api_version: 1

default_expiration: "12h"

handlers:

- url: /static
  static_dir: static 

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt 

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /tasks/.*
  script: main.py

- url: /user/.*
  script: main.py

- url: /.*
  script: main.py
