flowchart LR

    FluffyMac23( FluffyMac23 \n 10.2.6.229 \n 10.2.3.229 \n 10.1.4.11 )

cable[Shaw Cable] --> game(Game Nat \n 10.2.6.1)
game --> gameFast{ Game \n Yellow \n Fast Switch \n 10.2.6.2 }
gameFast -->|P?| gameSlow{ Game \n Slow Switch \n 10.2.6.3 }

gameSlow -->|P?| gameTV{ Game TV \n Slow Switch \n 10.2.6.4 }

homeFast -->|P?| homeServer( srvr17 \n 10.2.3.17 \n 10.1.8.17 )



    gameFast --> |P?| cOfficeW1((COffice \n ???))

    cOfficeW1 -->|P?| gameDeskFast{Game Desk \n Fast Switch \n 10.2.6.5 }

gameDeskFast --> |P?| FluffyMac23



    gameTV --> |p?| nintendoSwitch( Nintendo Switch )
    gameTV --> |p?| nvidiaSheild( Nvidia Sheild )
    gameTV --> |p?| appleTV( Apple TV )





dsl[Telus DSL] -->  home(Home Nat \n 10.2.3.1)
home --> homeFast{Home \n Green \nFast Switch \n 10.2.3.2}

homeFast-->  |P?| cOfficeW2((COffice \n ???))

    cOfficeW2 --> |P?| homeDeskFast{  Home Desk \n Fast Switch \n 10.2.3.5 }

homeDeskFast --> |P?| FluffyMac23

homeFast -->|P?| homeSlow{Home \n Slow Switch \n 10.2.3.3 }

homeSlow --> |P?| blueNat( Blue Nat )
blueNat --> |P?| blueSwitch{ Blue Switch \n not manged }

    blueSwitch --> |P?| FluffyMac23
blueSwitch --> |P?| srvr17( smail.fluffyhome.ca \n Server \n 10.1.4.13 )


homeSlow -->|P?| bwPrinter( BW Printer \n 10.2.3.21 )
homeSlow -->|P?| colorPrinter( Color Printer \n 10.2.3.22 )

    gameFast  -.->  cameraNat{ Camera Nat \n 10.1.8.1 }
    cameraNat --> cameraSlow

    cameraSlow{Camera \n TBD \nSlow POE Switch\n 10.1.8.2 }

    cameraSlow --> |P?| cam71( Camera 71 \n Side walkway \n 10.1.8.71 )
    cameraSlow -.-> |P?| cam72( Camera 72 \n Back Yard Low ?? \n Broken \n 10.1.8.71 )
    cameraSlow --> |P?| cam73( Camera 73 \n Side Driveway \n 10.1.8.73 )
    cameraSlow --> |P?| cam74( Camera 74 \n Critter Cam \n 10.1.8.74 )
    cameraSlow --> |P?| cam75( Camera 75 \n Side Deck & Walkway \n 10.1.8.75 )
    cameraSlow --> |P?| cam76( Camera 76 \n Deck \n 10.1.8.76 )
    cameraSlow --> |P?| cam77( Camera 77 \n Side Shed \n 10.1.8.77 )
    cameraSlow --> |P?| cam78( Camera 78 \n Front Door \n 10.1.8.78 )
    cameraSlow --> |P?| cam79( Camera 79 \n Back Yard High \n 10.1.8.79 )


    cameraSlow --> |p?| homeServer
